// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcM1jmPRI7tW8SWRlpOBK7xAnXcxTS1Q',
    appId: '1:871899433096:web:b0ca47e94c1df54b7d773d',
    messagingSenderId: '871899433096',
    projectId: 'shop-at-your-own-pace',
    authDomain: 'shop-at-your-own-pace.firebaseapp.com',
    storageBucket: 'shop-at-your-own-pace.firebasestorage.app',
    measurementId: 'G-YJXQCHEJWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGrGpy9CizVjSLHJBU91DNqu_K45a6rGc',
    appId: '1:871899433096:android:51f40f86051ad9c47d773d',
    messagingSenderId: '871899433096',
    projectId: 'shop-at-your-own-pace',
    storageBucket: 'shop-at-your-own-pace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLPbWfT99UkfRf2WyXruEURTXQRin99u4',
    appId: '1:871899433096:ios:c70faba362cf44637d773d',
    messagingSenderId: '871899433096',
    projectId: 'shop-at-your-own-pace',
    storageBucket: 'shop-at-your-own-pace.firebasestorage.app',
    androidClientId: '871899433096-eif9h00oa4qfs55088g6r8df00c6pafq.apps.googleusercontent.com',
    iosClientId: '871899433096-ftauub27dqofts0620vb5k2rqt4kivpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopatyourownpaceNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLPbWfT99UkfRf2WyXruEURTXQRin99u4',
    appId: '1:871899433096:ios:c70faba362cf44637d773d',
    messagingSenderId: '871899433096',
    projectId: 'shop-at-your-own-pace',
    storageBucket: 'shop-at-your-own-pace.firebasestorage.app',
    androidClientId: '871899433096-eif9h00oa4qfs55088g6r8df00c6pafq.apps.googleusercontent.com',
    iosClientId: '871899433096-ftauub27dqofts0620vb5k2rqt4kivpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopatyourownpaceNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzcM1jmPRI7tW8SWRlpOBK7xAnXcxTS1Q',
    appId: '1:871899433096:web:6a231f6db92327f57d773d',
    messagingSenderId: '871899433096',
    projectId: 'shop-at-your-own-pace',
    authDomain: 'shop-at-your-own-pace.firebaseapp.com',
    storageBucket: 'shop-at-your-own-pace.firebasestorage.app',
    measurementId: 'G-5YGPDNN328',
  );
}
